import Container from "@/components/Container";
import React from "react";

export default function TermsCondition() {
  return (
    <Container className="min-h-screen w-full py-12 px-4 md:py-16 md:px-8">
      <div className="max-w-5xl mx-auto mt-12 md:mt-20">
        {/* Heading */}
        <div className="mb-8 md:mb-12 text-center">
          <h1 className="text-2xl md:text-4xl font-bold mb-4">
            Terms & Conditions
          </h1>
          <p className="text-gray-600 text-sm md:text-base">
            Please read these terms carefully before using our platform
          </p>
        </div>

        {/* Content */}
        <div className="text-gray-800 leading-relaxed space-y-6 text-sm md:text-base">
          <ul className="list-disc list-inside space-y-4">
            <li>
              This document is an electronic record in terms of the Information
              Technology Act, 2000 and rules thereunder as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </li>
            <li>
              This document is published in accordance with the provisions of
              Rule 3 (1) of the Information Technology (Intermediaries
              guidelines) Rules, 2011 that require publishing the rules and
              regulations, privacy policy and Terms of Use for access or usage
              of domain name https://revupbikes.com (‘Website’), including the
              related mobile site and mobile application (hereinafter referred
              to as ‘Platform’).
            </li>
            <li>
              The Platform is owned by Revup, a company incorporated under the
              Companies Act, 1956 with its registered office at S no 10
              Mahatmafule Vasahat, Saswad rasat, near navrang mitra mandal,
              Pune, India (hereinafter referred to as ‘Platform Owner’, ‘we’,
              ‘us’, ‘our’).
            </li>
            <li>
              Your use of the Platform and services and tools are governed by
              the following terms and conditions (“Terms of Use”) as applicable
              to the Platform including the applicable policies which are
              incorporated herein by way of reference. If you transact on the
              Platform, you shall be subject to the policies that are applicable
              to the Platform for such transaction.
            </li>
            <li>
              For the purpose of these Terms of Use, wherever the context so
              requires ‘you’, ‘your’ or ‘user’ shall mean any natural or legal
              person who has agreed to become a user/buyer on the Platform.
            </li>
            <li className="font-semibold">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR
              AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF
              USE. PLEASE READ THEM CAREFULLY.
            </li>
            <li>
              To access and use the Services, you agree to provide true,
              accurate and complete information to us during and after
              registration, and you shall be responsible for all acts done
              through the use of your registered account.
            </li>
            <li>
              Neither we nor any third parties provide any warranty or guarantee
              as to the accuracy, timeliness, performance, completeness or
              suitability of the information and materials offered on this
              website or through the Services, for any specific purpose.
            </li>
            <li>
              Your use of our Services and the Platform is solely and entirely
              at your own risk and discretion for which we shall not be liable
              to you in any manner.
            </li>
            <li>
              The contents of the Platform and the Services are proprietary to
              us and are licensed to us. You will not have any authority to
              claim any intellectual property rights, title, or interest in its
              contents.
            </li>
            <li>
              You acknowledge that unauthorized use of the Platform and/or the
              Services may lead to action against you as per these Terms of Use
              and/or applicable laws.
            </li>
            <li>
              You agree to pay us the charges associated with availing the
              Services.
            </li>
            <li>
              You agree not to use the Platform and/ or Services for any purpose
              that is unlawful, illegal or forbidden by these Terms, or Indian
              or local laws that might apply to you.
            </li>
            <li>
              You agree and acknowledge that website and the Services may
              contain links to other third-party websites. On accessing these
              links, you will be governed by the terms of use, privacy policy
              and other policies of such third-party websites.
            </li>
            <li>
              You shall indemnify and hold harmless the Platform Owner, its
              affiliates, group companies and their officers from any claim or
              demand due to or arising out of your breach of these Terms or
              violation of law.
            </li>
            <li>
              Notwithstanding anything contained in these Terms of Use, the
              parties shall not be liable for any failure to perform an
              obligation under these Terms if performance is prevented or
              delayed by a force majeure event.
            </li>
            <li>
              These Terms and any dispute or claim relating to it shall be
              governed by and construed in accordance with the laws of India.
            </li>
            <li>
              All disputes shall be subject to the exclusive jurisdiction of the
              courts in Pune, Maharashtra.
            </li>
          </ul>
        </div>
      </div>
    </Container>
  );
}
